### ISSUE TITLE
Nhiệm vụ từ ngày 19/11 /2022 - 29/11/2022

### ISSUE THREAD

**Issue by meowmilk7202** [meowmilk7202/Sprint-1#1]
1. Nhóm chọn chức năng để code cho đề tài cuối kỳ
 Link : https://docs.google.com/document/d/1jirjYF2bO-Q24pyGhhDMu94oGU3HchdpZF7yfs-e8RE/edit?usp=sharing

**Comment by meowmilk7202** [comment]
Yêu cầu :
			-Daily Room -
Chọn chức năng thực thi trong 7g
Học hàng ngày liệt kê chức năng
Hôm qua làm đc gì, mô hình triển khai hôm nay
Chọn chức năng triển khai
Nộp lại link tài liệu backblog
Họp meet ghi lại lần làm việc -> Daily Srucm backblog
Đặt ít nhất 1 câu hỏi (gồm 3 câu để triển khai)
làm liên tục trong 7 ngày		
			- Debug and Version -
Tiêu chí chấm điểm : Contributions
		     Commit

Tạo branch rồi compare như Công Thành làm

**Comment by 81Quanghuy** [comment]
Can you create a tab project for management our project ?

**Comment by CongThanh27** [comment]
Can you give me a specific meeting time?
